services:
  - type: web
    name: casita-paula-agueda
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: casita-db
          property: connectionString

databases:
  - name: casita-db
    plan: free
    databaseName: casita
    user: casita
